version: "3"
services:
    openvpn:
        build: .
        image: vpnserver
        container_name: vpnserver
        ports:
            - "1194:1194/udp"
        devices:
            - "/dev/net/tun:/dev/net/tun"
        cap_add:
            - NET_ADMIN
        network_mode: host
        restart: always

