version: "3"
services:
    smbd:
        build: ./smbd
        image: gturta/smbd
        ports: 
         - "139:139/tcp"
         - "445:445/tcp"
        volumes:
         - /mnt/storage:/mnt
        tty: true
        restart: unless-stopped

    nmbd:
        build: ./nmbd
        image: gturta/nmbd
        ports:
            - "137:137/udp"
            - "138:138/udp"
        tty: true
        restart: unless-stopped

    cups:
        build: ./cups
        image: gturta/cups
        hostname: cups.turta.ro
        ports:
            - "631:631/tcp"
        restart: unless-stopped
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt

    avahi:
        build: ./avahi
        image: gturta/avahi
        ports:
            - "5353:5353/udp"
        network_mode: "host"
        restart: unless-stopped

networks:
  default:
    external:
      name: docker-net

