version: "3.2"
services:
    smbd:
        build: ./smbd
        image: gturta/smbd
        container_name: fileserver_smbd
        ports: 
         - "139:139/tcp"
         - "445:445/tcp"
        volumes:
            - type: bind
              source: /mnt/storage
              target: /mnt/storage
              bind:
                  #this is not working, better manually create the container
                  propagation: "shared"
        tty: true
        restart: unless-stopped

    nmbd:
        build: ./nmbd
        image: gturta/nmbd
        container_name: fileserver_nmbd
        ports:
            - "137:137/udp"
            - "138:138/udp"
        tty: true
        restart: unless-stopped

    cups:
        build: ./cups
        image: gturta/cups
        container_name: fileserver_cups
        hostname: cups.turta.ro
        ports:
            - "631:631/tcp"
        restart: unless-stopped
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt

    avahi:
        build: ./avahi
        image: gturta/avahi
        container_name: fileserver_avahi
        ports:
            - "5353:5353/udp"
        network_mode: "host"
        restart: unless-stopped

networks:
  default:
    external:
      name: docker-net

