version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="Europe/Bucharest"
      - PLEX_CLAIM="claim-5KAp2Bhx9soqNPx9bKBz"
      - ADVERTISE_IP=http://172.20.1.10:32400/
    hostname: plex
    volumes:
      - plex-db:/config
      - plex-transcode:/transcode
      - /mnt/storage/Media:/data

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - "8989:8989/tcp"
    environment:
      - TZ="Europe/Bucharest"
    volumes:
      - sonarr-db:/config
      - /mnt/storage/Media/Movies/Seriale/:/tv
      - /mnt/storage/Downloads/torrents/downloaded/:/downloads
    
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - "7878:7878/tcp"
    environment:
      - TZ="Europe/Bucharest"
    volumes:
      - radarr-db:/config
      - /mnt/storage/Media/Movies/Filme/:/movies
      - /mnt/storage/Downloads/torrents/downloaded/:/downloads
    
volumes:
  plex-db:
      external: true
  plex-transcode:
      external: true
  sonarr-db:
      external: true
  radarr-db:
      external: true

networks:
  default:
    external:
      name: docker-net

