version: "3"
services:
  plex:
    build: ./plex
    image: plex_vaapi 
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ="Europe/Bucharest"
    volumes:
      - plex-db:/config
      - plex-transcode:/transcode
      - /mnt/storage/Media:/data
      - /mnt/storage/Downloads:/downloads
    network_mode: host
    devices:
        - /dev/dri:/dev/dri

  sonarr:
    container_name: mediabox_sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - "8989:8989/tcp"
    environment:
      - TZ="Europe/Bucharest"
    volumes:
      - sonarr-db:/config
      - /mnt/storage/Media/Movies/Seriale/:/tv
      - /mnt/storage/Downloads/torrents/:/downloads
    
  radarr:
    container_name: mediabox_radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - "7878:7878/tcp"
    environment:
      - TZ="Europe/Bucharest"
    volumes:
      - radarr-db:/config
      - /mnt/storage/Media/Movies/Filme/:/movies
      - /mnt/storage/Downloads/torrents/:/downloads
    
  jackett:
    container_name: mediabox_jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "9117:9117/tcp"
    environment:
      - TZ="Europe/Bucharest"
    volumes:
      - jackett-db:/config
      - /mnt/storage/Downloads/torrents/input/:/downloads

volumes:
  plex-db:
      external: true
  plex-transcode:
      external: true
  sonarr-db:
      external: true
  radarr-db:
      external: true
  jackett-db:
      external: true


networks:
  default:
    external:
      name: docker-net
